apiVersion: v1
kind: Service
metadata:
  name: {{ include "coreason-platform.fullname" . }}
  labels:
    {{- include "coreason-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "coreason-platform.name" . }}
