name: Bandit Security Scan

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: '0 0 * * *'

permissions: read-all

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  bandit:
    name: Bandit Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Install Bandit"
        run: pip install bandit[sarif]

      - name: "Run Bandit"
        run: bandit -r . -f sarif -o bandit-results.sarif -s B101,B404 || true

      - name: "Upload Bandit results"
        uses: github/codeql-action/upload-sarif@458d36d7d4f47d0dd16ca424c1d3cda0060f1360 # v3.35.5
        with:
          sarif_file: 'bandit-results.sarif'


